# Project
version=2.0.2
group=com.nyfaria.anotherqualityoreset
java_version=17

# Common
minecraft_version=1.20.1
minecraft_version_range=[1.20,1.21)

# Mod options
mod_name=Another Quality Ore Set
mod_author=anotherqualityoreset
mod_id=anotherqualityoreset
description=Adds four new dimension-themed sets with unique tools and armor!
license=ARR
credits=

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Publishing
curseforge_publishing_enabled=true
curseforge_project_id=904782
modrinth_publishing_enabled=false
modrinth_project_id=0
dry_run=false